# Generated by Django 3.2.20 on 2023-09-08 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230908_1215'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipetag',
            name='unique_tag_in_recipe',
        ),
        migrations.AlterUniqueTogether(
            name='recipetag',
            unique_together={('tag', 'recipe')},
        ),
    ]
