# Generated by Django 3.2.21 on 2023-09-18 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20230917_1816'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
