# Generated by Django 3.2.21 on 2023-09-29 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Введите логин', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Введите допустимое значение', regex='^[\\w.@+-]+\\Z')], verbose_name='Логин'),
        ),
    ]
